FROM nginx

MAINTAINER "Ivan Ermilov <mailto:ivan.s.ermilov@gmail.com>"

COPY nginx/default.conf /etc/nginx/conf.d/default.conf
COPY nginx/materialize.min.css /data/bde-css/materialize.min.css
COPY nginx/bde-hadoop.css /data/bde-css/bde-hadoop.css
